# templates/db-pvc.yaml

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.db.persistence.size }}
  volumeMode: {{ .Values.db.volumeMode }}
  storageClassName: {{ .Values.db.storageClassName }}
