# templates/traefik-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      containers:
        - name: traefik
          image: {{ .Values.traefik.image }}
          args:
            - "--providers.kubernetescrd"
            - "--entrypoints.web.address=:80"
            - "--entrypoints.metrics.address=:8082"
            - "--metrics.prometheus=true"
            - "--metrics.prometheus.entryPoint=metrics"
          ports:
            - name: http
              containerPort: {{ .Values.traefik.port.http }}
            - name: metrics
              containerPort: {{ .Values.traefik.port.metrics }}
